package providers

import (
	"log"
	"reflect"
	"strings"

	"gopkg.in/yaml.v3"
)

// removedMainConfigKeys lists the keys that no longer belong to the runtime
// contract. They used to be parsed into a field nobody read, which made them
// look like settings; every field MainConfig declares today is used by the
// framework, so these are reported as leftovers to delete instead.
var removedMainConfigKeys = map[string]string{
	"paths.model_folder": "only the v0.5 CLI reads it",
	"paths.project_name": "only the v0.5 CLI reads it",
	"paths.main_file":    "only the v0.5 CLI reads it",
}

// renamedMainConfigKeys maps the keys generated by the v0.5 CLI templates to
// their v2 name. They are unknown keys like any other typo, but the warning
// can name the replacement instead of leaving the reader to guess.
var renamedMainConfigKeys = map[string]string{
	"paths.api_folder": "paths.route_folder",
	"database.dbname":  "database.db",
}

var yamlUnmarshalerType = reflect.TypeOf((*yaml.Unmarshaler)(nil)).Elem()

// warnAboutDeadConfigKeys reports the keys of a config file that have no
// effect: keys the config struct does not declare — typos, or leftovers from
// the v0.5 CLI templates — and keys it declares but nothing reads.
//
// Both are warnings, never errors: yaml.v3 has always ignored unknown keys
// here, so failing on them would stop applications that boot fine today.
func warnAboutDeadConfigKeys(filePath string, content []byte, cfg any) {
	var document yaml.Node
	if err := yaml.Unmarshal(content, &document); err != nil {
		// The caller already turns the parse error into a real failure.
		return
	}

	root := mappingRoot(&document)
	if root == nil {
		return
	}

	_, isMainConfig := cfg.(*MainConfig)

	for _, key := range unknownKeys(root, reflect.TypeOf(cfg)) {
		if !isMainConfig {
			log.Printf("⚠️  %s: unknown key %q — the value is ignored", filePath, key)
			continue
		}

		switch {
		case renamedMainConfigKeys[key] != "":
			log.Printf("⚠️  %s: %q was renamed to %q — the value is ignored", filePath, key, renamedMainConfigKeys[key])
		case removedMainConfigKeys[key] != "":
			log.Printf("⚠️  %s: %q is not a runtime setting (%s) — delete it", filePath, key, removedMainConfigKeys[key])
		default:
			log.Printf("⚠️  %s: unknown key %q — the value is ignored", filePath, key)
		}
	}
}

// mappingRoot returns the top-level mapping of a parsed document, or nil when
// the file is empty or holds something else than a mapping.
func mappingRoot(document *yaml.Node) *yaml.Node {
	node := document
	if node.Kind == yaml.DocumentNode {
		if len(node.Content) == 0 {
			return nil
		}
		node = node.Content[0]
	}
	if node.Kind != yaml.MappingNode {
		return nil
	}
	return node
}

// unknownKeys returns the dotted path of every key of a YAML mapping that the
// Go type it is unmarshalled into does not declare, in file order.
func unknownKeys(node *yaml.Node, typ reflect.Type) []string {
	var unknown []string
	collectUnknownKeys(node, typ, "", &unknown)
	return unknown
}

// collectUnknownKeys walks a YAML mapping alongside its Go type. Only structs
// are walked: a map accepts any key, and a slice or a scalar has no key to
// check. A type with its own UnmarshalYAML decides what its node means, so its
// children are left alone.
func collectUnknownKeys(node *yaml.Node, typ reflect.Type, prefix string, unknown *[]string) {
	typ = derefType(typ)
	if node.Kind != yaml.MappingNode || typ.Kind() != reflect.Struct || hasYAMLUnmarshaler(typ) {
		return
	}

	fields := yamlFields(typ)
	for i := 0; i+1 < len(node.Content); i += 2 {
		name, value := node.Content[i].Value, node.Content[i+1]
		key := prefix + name

		fieldType, declared := fields[name]
		if !declared {
			*unknown = append(*unknown, key)
			continue
		}

		fieldType = derefType(fieldType)
		switch fieldType.Kind() {
		case reflect.Struct:
			collectUnknownKeys(value, fieldType, key+".", unknown)
		case reflect.Map:
			// The keys of a map are data, not field names: only the values
			// are checked against the element type.
			if value.Kind != yaml.MappingNode {
				continue
			}
			for j := 0; j+1 < len(value.Content); j += 2 {
				entry := key + "." + value.Content[j].Value
				collectUnknownKeys(value.Content[j+1], fieldType.Elem(), entry+".", unknown)
			}
		}
	}
}

// yamlFields maps the YAML keys a struct declares to the type of the field
// behind them, following the naming rules of yaml.v3: the name of the tag, or
// the lowercased field name when the tag has none.
func yamlFields(typ reflect.Type) map[string]reflect.Type {
	fields := map[string]reflect.Type{}

	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if field.PkgPath != "" {
			continue
		}

		name, options, _ := strings.Cut(field.Tag.Get("yaml"), ",")
		if name == "-" {
			continue
		}
		if strings.Contains(options, "inline") && derefType(field.Type).Kind() == reflect.Struct {
			for inlineName, inlineType := range yamlFields(derefType(field.Type)) {
				fields[inlineName] = inlineType
			}
			continue
		}
		if name == "" {
			name = strings.ToLower(field.Name)
		}
		fields[name] = field.Type
	}

	return fields
}

func derefType(typ reflect.Type) reflect.Type {
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	return typ
}

func hasYAMLUnmarshaler(typ reflect.Type) bool {
	return typ.Implements(yamlUnmarshalerType) || reflect.PointerTo(typ).Implements(yamlUnmarshalerType)
}
