app_name: "my_api"
version: "1.0.0"
mode: "development"

server:
  port: 8080
  cors: true

database:
  type: "postgres"
  user: "admin"
  password: "admin"
  host: "localhost"
  port: 5432
  dbname: "yogourtDB"

paths:
  model_folder: "my_api/models/"
  project_name: "my_api"
  main_file: "my_api/main.go"
  route_folder: "my_api/routes/"
