app_name: "my_api"
version: "1.0.0"
mode: "development"

server:
  host: "127.0.0.1"
  port: 8080
  cors: true

database:
  type: "postgres"
  user: "admin"
  password: "password"
  host: "localhost"
  port: 5432
  dbname: "mydb"

auth:
  jwt_secret: "supersecretkey"
  token_expiry: 3600

logs:
  level: "debug"
  file: "logs/app.log"
