package database

import (
	"database/sql"
	"errors"
	"os"
	"testing"

	"github.com/goyourt/yogourt/interfaces"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// auditRecord is a throwaway model embedding interfaces.Base: it carries the
// audit columns whose persistence is under test.
type auditRecord struct {
	interfaces.Base
	Name string
}

func (auditRecord) TableName() string { return "audit_records" }

// openDB connects to the PostgreSQL instance designated by YOGOURT_TEST_DSN,
// skipping the test when the variable is not set. Same convention as
// authorization/gormstore/gormstore_test.go.
func openDB(t *testing.T) *gorm.DB {
	t.Helper()

	dsn := os.Getenv("YOGOURT_TEST_DSN")
	if dsn == "" {
		t.Skip("YOGOURT_TEST_DSN not set; skipping PostgreSQL integration tests")
	}

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open database: %v", err)
	}

	return db
}

// setupAuditTable migrates the throwaway model and starts each test from an
// empty table.
func setupAuditTable(t *testing.T) *gorm.DB {
	t.Helper()

	db := openDB(t)
	if err := db.AutoMigrate(&auditRecord{}); err != nil {
		t.Fatalf("migrate: %v", err)
	}
	if err := db.Exec(`TRUNCATE audit_records RESTART IDENTITY CASCADE`).Error; err != nil {
		t.Fatalf("truncate audit_records: %v", err)
	}

	return db
}

func createAuditRecord(t *testing.T, db *gorm.DB, name string) *auditRecord {
	t.Helper()

	record := &auditRecord{Name: name}
	if err := db.Create(record).Error; err != nil {
		t.Fatalf("create %s: %v", name, err)
	}
	// Reload so uuid, generated by gen_random_uuid(), is known.
	if err := db.First(record, "id = ?", record.GetID()).Error; err != nil {
		t.Fatalf("reload %s: %v", name, err)
	}

	return record
}

// readAuditColumns reads the raw columns, bypassing GORM's soft-delete scope:
// what is asserted is what PostgreSQL actually stores.
func readAuditColumns(t *testing.T, db *gorm.DB, uuid string) (sql.NullTime, sql.NullInt64) {
	t.Helper()

	var deletedAt sql.NullTime
	var deletedByID sql.NullInt64

	row := db.Raw(`SELECT deleted_at, deleted_by_id FROM audit_records WHERE uuid = ?`, uuid).Row()
	if err := row.Scan(&deletedAt, &deletedByID); err != nil {
		t.Fatalf("read audit columns of %s: %v", uuid, err)
	}

	return deletedAt, deletedByID
}

func countAuditRecords(t *testing.T, db *gorm.DB, uuid string) int64 {
	t.Helper()

	var n int64
	if err := db.Raw(`SELECT COUNT(*) FROM audit_records WHERE uuid = ?`, uuid).Scan(&n).Error; err != nil {
		t.Fatalf("count rows of %s: %v", uuid, err)
	}

	return n
}

// GORM's soft-delete callback only writes deleted_at; deleted_by_id used to
// stay NULL forever. Both columns must now be set by Delete.
func TestSoftDeletePersistsDeletedById(t *testing.T) {
	db := setupAuditTable(t)

	currentUser := createAuditRecord(t, db, "current-user")
	record := createAuditRecord(t, db, "to-delete")

	writer := DataWriter{CurrentUser: currentUser}
	if err := writer.softDelete(db, record); err != nil {
		t.Fatalf("soft delete: %v", err)
	}

	deletedAt, deletedByID := readAuditColumns(t, db, record.GetUuid())
	if !deletedAt.Valid {
		t.Error("deleted_at must be set after a soft delete")
	}
	if !deletedByID.Valid {
		t.Fatal("deleted_by_id must be persisted after a soft delete, got NULL")
	}
	if deletedByID.Int64 != int64(currentUser.GetID()) {
		t.Errorf("deleted_by_id must be %d, got %d", currentUser.GetID(), deletedByID.Int64)
	}

	// The soft delete itself must keep its meaning: the row is still there but
	// invisible to a normal read.
	if got := countAuditRecords(t, db, record.GetUuid()); got != 1 {
		t.Errorf("a soft deleted row must remain in the table, found %d", got)
	}
	err := db.First(&auditRecord{}, "uuid = ?", record.GetUuid()).Error
	if !errors.Is(err, gorm.ErrRecordNotFound) {
		t.Errorf("a soft deleted row must not be readable anymore, got %v", err)
	}

	// UpdateColumn must not behave like an update: a deletion is not a
	// modification, updated_at and updated_by_id stay as they were.
	var updatedAt sql.NullTime
	var updatedByID sql.NullInt64
	row := db.Raw(`SELECT updated_at, updated_by_id FROM audit_records WHERE uuid = ?`, record.GetUuid()).Row()
	if err := row.Scan(&updatedAt, &updatedByID); err != nil {
		t.Fatalf("read update columns: %v", err)
	}
	if !updatedAt.Time.Equal(record.GetUpdatedAt().UTC()) {
		t.Errorf("updated_at must not be bumped by the audit statement: %v vs %v", updatedAt.Time, record.GetUpdatedAt().UTC())
	}
	if updatedByID.Valid {
		t.Error("updated_by_id must not be written by a deletion")
	}

	// The other rows are untouched: the audit statement targets one uuid.
	_, userDeletedByID := readAuditColumns(t, db, currentUser.GetUuid())
	if userDeletedByID.Valid {
		t.Error("the audit statement must not touch another row")
	}
}

// Without an authenticated user there is no audit column to write, and the
// plain soft delete must still happen.
func TestSoftDeleteWithoutCurrentUser(t *testing.T) {
	db := setupAuditTable(t)

	record := createAuditRecord(t, db, "to-delete")

	writer := DataWriter{CurrentUser: nil}
	if err := writer.softDelete(db, record); err != nil {
		t.Fatalf("soft delete: %v", err)
	}

	deletedAt, deletedByID := readAuditColumns(t, db, record.GetUuid())
	if !deletedAt.Valid {
		t.Error("deleted_at must be set even without a current user")
	}
	if deletedByID.Valid {
		t.Errorf("deleted_by_id must stay NULL without a current user, got %d", deletedByID.Int64)
	}
}

// HardDelete must still remove the row for good.
func TestHardDeleteRemovesRow(t *testing.T) {
	db := setupAuditTable(t)

	record := createAuditRecord(t, db, "to-hard-delete")

	if err := hardDelete(db, record); err != nil {
		t.Fatalf("hard delete: %v", err)
	}

	if got := countAuditRecords(t, db, record.GetUuid()); got != 0 {
		t.Errorf("a hard deleted row must be gone, found %d", got)
	}
}

// A soft deleted row can then be hard deleted: the audit write must not lock
// the row out of a later purge.
func TestHardDeleteAfterSoftDelete(t *testing.T) {
	db := setupAuditTable(t)

	currentUser := createAuditRecord(t, db, "current-user")
	record := createAuditRecord(t, db, "to-delete-twice")

	writer := DataWriter{CurrentUser: currentUser}
	if err := writer.softDelete(db, record); err != nil {
		t.Fatalf("soft delete: %v", err)
	}
	if err := hardDelete(db, record); err != nil {
		t.Fatalf("hard delete: %v", err)
	}

	if got := countAuditRecords(t, db, record.GetUuid()); got != 0 {
		t.Errorf("a hard deleted row must be gone, found %d", got)
	}
}
