package interfaces

import (
	"time"

	"gorm.io/gorm"
)

type WithID struct {
	ID *int `gorm:"primaryKey;autoIncrement" json:"-"`
}

func (w *WithID) ResetGeneratedIdentity() { w.ID = nil }

func (w *WithID) AuditActorID() (int, bool) {
	if w.ID == nil || *w.ID == 0 {
		return 0, false
	}
	return *w.ID, true
}

// WithUuid carries a public identity backed by another primary key. The uuid
// is generated by the database default, so Create resets it: a bound payload
// must not choose it.
type WithUuid struct {
	Uuid *string `gorm:"type:uuid;default:gen_random_uuid();not null;unique" json:"uuid"`
}

func (w *WithUuid) ResetGeneratedIdentity() { w.Uuid = nil }

func (w *WithUuid) GetPublicId() string {
	if w.Uuid == nil {
		return ""
	}
	return *w.Uuid
}

func (w *WithUuid) PublicIdColumn() string { return "uuid" }

// WithUuidPK makes the public identity the primary key itself.
type WithUuidPK struct {
	Uuid *string `gorm:"primaryKey;type:uuid;default:gen_random_uuid()" json:"uuid"`
}

func (w *WithUuidPK) GetPublicId() string {
	if w.Uuid == nil {
		return ""
	}
	return *w.Uuid
}

func (w *WithUuidPK) PublicIdColumn() string { return "uuid" }

func (w *WithUuidPK) ResetGeneratedIdentity() { w.Uuid = nil }

type WithTimestamps struct {
	CreatedAt time.Time `json:"createdAt" gorm:"autoCreateTime"`
	UpdatedAt time.Time `json:"updatedAt" gorm:"autoUpdateTime"`
}

func (w *WithTimestamps) SetUpdatedAt(t time.Time) { w.UpdatedAt = t }

type WithAudit struct {
	CreatedById *int `json:"-"`
	UpdatedById *int `json:"-"`
}

func (w *WithAudit) SetCreatedBy(actorId int) { w.CreatedById = &actorId }

func (w *WithAudit) SetUpdatedBy(actorId int) { w.UpdatedById = &actorId }

type WithSoftDelete struct {
	DeletedAt   gorm.DeletedAt `json:"-" gorm:"index"`
	DeletedById *int           `json:"-"`
}

func (w *WithSoftDelete) DeleteAuditAssignment(actorId int) (string, any) {
	return "deleted_by_id", actorId
}

// Base is the full preset: integer primary key, public uuid, timestamps,
// write audit and audited soft delete.
type Base struct {
	WithID
	WithUuid
	WithTimestamps
	WithAudit
	WithSoftDelete
}

func (b *Base) ResetGeneratedIdentity() {
	b.WithID.ResetGeneratedIdentity()
	b.WithUuid.ResetGeneratedIdentity()
}

var (
	_ Resource                  = (*WithUuid)(nil)
	_ Resource                  = (*WithUuidPK)(nil)
	_ Resource                  = (*Base)(nil)
	_ GeneratedIdentityResetter = (*WithID)(nil)
	_ GeneratedIdentityResetter = (*WithUuid)(nil)
	_ GeneratedIdentityResetter = (*WithUuidPK)(nil)
	_ GeneratedIdentityResetter = (*Base)(nil)
	_ AuditActorProvider        = (*WithID)(nil)
	_ CreatedBySetter           = (*WithAudit)(nil)
	_ UpdatedBySetter           = (*WithAudit)(nil)
	_ UpdatedAtSetter           = (*WithTimestamps)(nil)
	_ DeleteAuditor             = (*WithSoftDelete)(nil)
)
