package interfaces

import "time"

// Resource is the only interface the framework ever requires, and only where
// an operation is meaningless without a public identity: HandleRequest
// hydration, Authenticate, UpsertRelations and the derived authorization
// subject. CRUD helpers accept any model.
type Resource interface {
	GetPublicId() string
	PublicIdColumn() string
}

// GeneratedIdentityResetter is implemented by models whose identity is
// generated by the database (auto-increment key, defaulted uuid). Create
// resets it: a client-supplied value must never be inserted as a generated
// identity. Application-assigned keys must not implement it and are never
// touched.
type GeneratedIdentityResetter interface {
	ResetGeneratedIdentity()
}

type CreatedBySetter interface {
	SetCreatedBy(actorId int)
}

type UpdatedBySetter interface {
	SetUpdatedBy(actorId int)
}

type UpdatedAtSetter interface {
	SetUpdatedAt(t time.Time)
}

// DeleteAuditor returns the column assignment recording who deleted the row.
// gorm.Delete only writes deleted_at, so the engine needs the assignment to
// emit it as a separate statement in the same transaction.
type DeleteAuditor interface {
	DeleteAuditAssignment(actorId int) (column string, value any)
}

// AuditActorProvider is implemented by the current user. ok is false when the
// actor has no usable identity yet; audit columns are then skipped rather
// than attributed to actor 0.
type AuditActorProvider interface {
	AuditActorID() (id int, ok bool)
}
